version: '3.1'
services:
  db:
    image: postgres
    container_name: 'ais_postgres'
    environment:
      - POSTGRES_DB=ais_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
